/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/models/car.glb 
Author: Renafox (https://sketchfab.com/kryik1023)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/old-rusty-car-2-544aa41de67b48cf89f8fcc2bb06e8f4
Title: Old Rusty Car 2
*/

import { useGLTF } from "@react-three/drei";
interface ModelProps {
  [key: string]: any
}
export function Car(props: ModelProps) {
  const { nodes, materials } = useGLTF("/models/car.glb") as any;
  return (
    <group {...props} dispose={null} scale={0.05}>
      <mesh
        geometry={nodes["Object001_Material_#37_0"].geometry}
        material={materials.Material_37}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["Object002_Material_#33_0"].geometry}
        material={materials.Material_33}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["Plane001_Material_#58_0"].geometry}
        material={materials.Material_58}
        position={[0.817, 1.861, -1.258]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.697, 1.12, 1]}
      />
    </group>
  );
}

useGLTF.preload("/models/car.glb");
