/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Converted to TSX
*/

import React, { useRef, useMemo, useEffect, forwardRef, useImperativeHandle } from "react";
import { Group, MeshStandardMaterial } from "three";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: any;
  materials: any;
};

type HorseProps = {
  color?: string;
  emmisiveIntensity?: number;
};

export const Horse1 = forwardRef((props: HorseProps, ref) => {
  const group = useRef<Group>(null);
  const { color = "#f5f5f5", emmisiveIntensity = 0.15, ...rest } = props;
  const { scene, animations } = useGLTF("/models/horse.glb") as GLTFResult;

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);

  const { nodes, materials } = useGraph(clone) as GLTFResult;

  const { actions } = useAnimations(animations, group);

  console.log("actions", actions, materials.Horse);
  // 🎨 Clone materials per instance
  const horseMaterial = useMemo(() => {
    const mat = materials.Horse.clone();

    mat.map = materials.Horse.map; // keep texture
    mat.color.set(color) // ✅ no multiplyScalar

    // mat.roughness = 0.8;
    // mat.metalness = 0.1;
    mat.emissive.set(color);
    mat.emissiveIntensity = emmisiveIntensity;
    mat.skinning = true; // ✅ IMPORTANT (add this)

    return mat;
  }, [materials, color, emmisiveIntensity]);

  useImperativeHandle(ref, () => ({
    actions,
  }));

  return (
    <group ref={group} {...props} dispose={null} scale={2}>
      <group name="Scene">
        <group name="horse_rig">
          <primitive object={nodes.c_pos} />
          <primitive object={nodes.c_foot_ikr} />
          <primitive object={nodes.c_leg_poler} />
          <primitive object={nodes.c_foot_ikl} />
          <primitive object={nodes.c_leg_polel} />
          <primitive object={nodes.root_refx} />
          <primitive object={nodes.c_foot_ik_dupli_001l} />
          <primitive object={nodes.c_leg_pole_dupli_001l} />
          <primitive object={nodes.c_foot_ik_dupli_001r} />
          <primitive object={nodes.c_leg_pole_dupli_001r} />
          <primitive object={nodes.c_spline_inter_01x} />
          <primitive object={nodes.c_spline_inter_02x} />
          <primitive object={nodes.c_spline_inter_03x} />
          <primitive object={nodes.eye_offset_refl} />
          <primitive object={nodes.c_eye_targetx} />
          <primitive object={nodes.eye_offset_refr} />
          <primitive object={nodes.bot_bend_refl} />
          <primitive object={nodes.bot_bend_refr} />

          <skinnedMesh
            name="eyel"
            geometry={nodes.eyel.geometry}
            material={horseMaterial}
            skeleton={nodes.eyel.skeleton}
          />
          <skinnedMesh
            name="eyer"
            geometry={nodes.eyer.geometry}
            material={horseMaterial}
            skeleton={nodes.eyer.skeleton}
          />
          <skinnedMesh
            name="horse_hair"
            geometry={nodes.horse_hair.geometry}
            material={materials.Horse_Hair}
            skeleton={nodes.horse_hair.skeleton}
          >
            {/* <meshStandardMaterial color={color} /> */}
          </skinnedMesh>
          <skinnedMesh
            name="belt_saddle"
            geometry={nodes.belt_saddle.geometry}
            material={materials.Horse_Outfit}
            skeleton={nodes.belt_saddle.skeleton}
            morphTargetDictionary={nodes.belt_saddle.morphTargetDictionary}
            morphTargetInfluences={nodes.belt_saddle.morphTargetInfluences}
          />

          <group name="Horse_Body">
            <skinnedMesh
              name="Mesh003"
              geometry={nodes.Mesh003.geometry}
              material={horseMaterial}
              skeleton={nodes.Mesh003.skeleton}
              morphTargetDictionary={nodes.Mesh003.morphTargetDictionary}
              morphTargetInfluences={nodes.Mesh003.morphTargetInfluences}

            >

            </skinnedMesh>
            <skinnedMesh
              name="Mesh003_1"
              geometry={nodes.Mesh003_1.geometry}
              material={materials.Horse_Hair}
              skeleton={nodes.Mesh003_1.skeleton}
              morphTargetDictionary={nodes.Mesh003_1.morphTargetDictionary}
              morphTargetInfluences={nodes.Mesh003_1.morphTargetInfluences}
            >
              {/* <meshStandardMaterial color={color} /> */}
            </skinnedMesh>
          </group>
        </group>
      </group>
    </group>
  );
})

useGLTF.preload("/models/horse.glb");

