/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/models/track.glb 
*/

import { useGLTF } from '@react-three/drei'
import { Group } from 'three'
import { useFrame, useThree } from '@react-three/fiber'
import { useRef } from 'react'
import * as THREE from 'three'

interface ModelProps {
  [key: string]: any
}
function Sky({ geometry, material }: any) {
  const ref = useRef<THREE.Mesh>(null!)
  const { camera } = useThree()

  useFrame(() => {
    if (ref.current) {
      ref.current.position.copy(camera.position)
    }
  })

  return (
    <mesh ref={ref} geometry={geometry} scale={0.83}>
      <meshBasicMaterial
        map={material.emissiveMap}
        side={2}
        color={[3, 3, 3]}
        toneMapped={false}
        depthWrite={false}

      />
    </mesh>
  )
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/models/RoadTest.glb') as any
  return (
    <group {...props} dispose={null}>

      {/* <Sky
        geometry={nodes.EnvironmentSphere.geometry}
        material={materials['Material.013']}
      /> */}



      <mesh geometry={nodes.TrackCliffs_Baked_Combined_Compressed.geometry} material={materials.TrackCliffs_Baked_Combined_Compressed} position={[617.033, -5.551, 182.431]} />
      <mesh geometry={nodes.LargeCliffs_Break_WithLighting_Combined_Compressed.geometry} material={materials.LargeCliffs_Break_WithLighting_Combined_Compressed} />
      <mesh geometry={nodes.LandscapeScatter_1_Combined_Compressed.geometry} material={materials.LandscapeScatter_1_Combined_Compressed} />
      <mesh geometry={nodes.Cactus_Scattering_Combined_Compressed.geometry} material={materials.Cactus_Scattering_Combined_Compressed} />
      <mesh geometry={nodes.LandscapeScatter_2_Combined_Compressed.geometry} material={materials.LandscapeScatter_2_Combined_Compressed} />
      <mesh geometry={nodes.LandscapeScatter_3_Combined_Compressed.geometry} material={materials.LandscapeScatter_3_Combined_Compressed} />
      <mesh geometry={nodes.LandscapeScatter_4_Combined_Compressed.geometry} material={materials.LandscapeScatter_4_Combined_Compressed} />
      <mesh name="Landscape_Combined_Compressed" geometry={nodes.Landscape_Combined_Compressed.geometry} material={materials.Landscape_Combined_Compressed} morphTargetDictionary={nodes.Landscape_Combined_Compressed.morphTargetDictionary} morphTargetInfluences={nodes.Landscape_Combined_Compressed.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/models/RoadTest.glb')
