/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 COW_BOY.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/COW_BOY.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="cowboy_rig">
          <primitive object={nodes.c_pos} />
          <primitive object={nodes.c_arms_polel} />
          <primitive object={nodes.c_arms_poler} />
          <primitive object={nodes.c_foot_ikr} />
          <primitive object={nodes.c_leg_poler} />
          <primitive object={nodes.c_foot_ikl} />
          <primitive object={nodes.c_leg_polel} />
          <primitive object={nodes.c_hand_ikr} />
          <primitive object={nodes.c_hand_ikl} />
          <primitive object={nodes.root_refx} />
          <skinnedMesh name="Bandage" geometry={nodes.Bandage.geometry} material={materials.Bandage_M} skeleton={nodes.Bandage.skeleton} />
          <skinnedMesh name="Belt" geometry={nodes.Belt.geometry} material={materials.Belt_M} skeleton={nodes.Belt.skeleton} />
          <skinnedMesh name="Boot" geometry={nodes.Boot.geometry} material={materials.Boot_M} skeleton={nodes.Boot.skeleton} />
          <skinnedMesh name="eye_AO" geometry={nodes.eye_AO.geometry} material={materials.eye_AO} skeleton={nodes.eye_AO.skeleton} />
          <group name="eye_brow">
            <skinnedMesh name="eye_browR" geometry={nodes.eye_browR.geometry} material={materials.eye_browR} skeleton={nodes.eye_browR.skeleton} />
            <skinnedMesh name="eye_browR_1" geometry={nodes.eye_browR_1.geometry} material={materials.eye_browL} skeleton={nodes.eye_browR_1.skeleton} />
          </group>
          <group name="eye_cornea">
            <skinnedMesh name="eye_cornea_1" geometry={nodes.eye_cornea_1.geometry} material={materials.eye_cornea} skeleton={nodes.eye_cornea_1.skeleton} />
            <skinnedMesh name="eye_cornea_2" geometry={nodes.eye_cornea_2.geometry} material={materials.eyes_cornea_blind} skeleton={nodes.eye_cornea_2.skeleton} />
          </group>
          <group name="eye_iris">
            <skinnedMesh name="eye_iris_1" geometry={nodes.eye_iris_1.geometry} material={materials.eye_irisBlind} skeleton={nodes.eye_iris_1.skeleton} />
            <skinnedMesh name="eye_iris_2" geometry={nodes.eye_iris_2.geometry} material={materials.eye_iris} skeleton={nodes.eye_iris_2.skeleton} />
          </group>
          <skinnedMesh name="eye_lashes" geometry={nodes.eye_lashes.geometry} material={materials.eye_lashes} skeleton={nodes.eye_lashes.skeleton} />
          <skinnedMesh name="eye_tearLine" geometry={nodes.eye_tearLine.geometry} material={materials['eye_tearLine.001']} skeleton={nodes.eye_tearLine.skeleton} />
          <skinnedMesh name="Hair_cap" geometry={nodes.Hair_cap.geometry} material={materials['Hair_cap.001']} skeleton={nodes.Hair_cap.skeleton} />
          <skinnedMesh name="Hair_cut" geometry={nodes.Hair_cut.geometry} material={materials.Hair} skeleton={nodes.Hair_cut.skeleton} />
          <skinnedMesh name="Hands_Optimized" geometry={nodes.Hands_Optimized.geometry} material={materials.Sheriff_hands} skeleton={nodes.Hands_Optimized.skeleton} />
          <skinnedMesh name="Hat" geometry={nodes.Hat.geometry} material={materials.Hat_M} skeleton={nodes.Hat.skeleton} />
          <skinnedMesh name="Holster" geometry={nodes.Holster.geometry} material={materials.Holster_M} skeleton={nodes.Holster.skeleton} />
          <skinnedMesh name="Jacket_Optimized" geometry={nodes.Jacket_Optimized.geometry} material={materials.Jacket_M} skeleton={nodes.Jacket_Optimized.skeleton} />
          <skinnedMesh name="Jeans" geometry={nodes.Jeans.geometry} material={materials.Jeans_M} skeleton={nodes.Jeans.skeleton} />
          <skinnedMesh name="Michael_head" geometry={nodes.Michael_head.geometry} material={materials.Michael_head} skeleton={nodes.Michael_head.skeleton} />
          <skinnedMesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} skeleton={nodes.Plane.skeleton} />
          <skinnedMesh name="Raincoat" geometry={nodes.Raincoat.geometry} material={materials.Raincpat_M} skeleton={nodes.Raincoat.skeleton} />
          <skinnedMesh name="Scarf" geometry={nodes.Scarf.geometry} material={materials.Scarf_M} skeleton={nodes.Scarf.skeleton} />
          <skinnedMesh name="Shirt_Optimized_2" geometry={nodes.Shirt_Optimized_2.geometry} material={materials.Shirt_M} skeleton={nodes.Shirt_Optimized_2.skeleton} />
          <skinnedMesh name="Tongue_1" geometry={nodes.Tongue_1.geometry} material={materials.Tongue_1_lambert} skeleton={nodes.Tongue_1.skeleton} />
        </group>
        <group name="char_grp002" />
      </group>
    </group>
  )
}

useGLTF.preload('/COW_BOY.glb')
